export const BISAC_CODES = [
  { code: "FIC000000", label: "FICTION / General" },
  { code: "FIC002000", label: "FICTION / Action & Adventure" },
  { code: "FIC004000", label: "FICTION / Classics" },
  { code: "FIC009000", label: "FICTION / Fantasy / General" },
  { code: "FIC009010", label: "FICTION / Fantasy / Epic" },
  { code: "FIC014000", label: "FICTION / Historical / General" },
  { code: "FIC015000", label: "FICTION / Horror" },
  { code: "FIC019000", label: "FICTION / Literary" },
  { code: "FIC022000", label: "FICTION / Mystery & Detective / General" },
  { code: "FIC024000", label: "FICTION / Noir" },
  { code: "FIC027000", label: "FICTION / Romance / General" },
  { code: "FIC028000", label: "FICTION / Science Fiction / General" },
  { code: "FIC028010", label: "FICTION / Science Fiction / Space Opera" },
  { code: "FIC031000", label: "FICTION / Thrillers / General" },
  { code: "FIC033000", label: "FICTION / Westerns" },
  { code: "BIO000000", label: "BIOGRAPHY & AUTOBIOGRAPHY / General" },
  { code: "BUS000000", label: "BUSINESS & ECONOMICS / General" },
  { code: "HIS000000", label: "HISTORY / General" },
  { code: "SOC000000", label: "SOCIAL SCIENCE / General" },
  { code: "PHI000000", label: "PHILOSOPHY / General" },
];
